const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { auditSnapshot } = require("../shared/audit-engine.js");

const snapshot = JSON.parse(fs.readFileSync(path.join(__dirname, "fixtures/inaccessible-snapshot.json"), "utf8"));
const result = auditSnapshot(snapshot);
const byElement = (id) => result.issues.filter((issue) => issue.element_id === id);
assert.ok(byElement("el-main>img").some((issue) => issue.id.startsWith("image-alt:")), "missing-alt finding references image");
assert.ok(byElement("el-main>button").some((issue) => issue.id.startsWith("name:")), "unlabeled-button finding references button");
assert.ok(byElement("el-main>button").some((issue) => issue.id.startsWith("target:")), "small-target finding references button");
assert.ok(byElement("el-main>h1").some((issue) => issue.id.startsWith("contrast:")), "contrast finding references text node");
assert.ok(result.issueCount >= 4);
assert.ok(result.severity.high >= 2);
assert.ok(result.issues.every((issue) => issue.id && issue.element_id && issue.wcag_reference && issue.detected_by && typeof issue.can_auto_fix === "boolean"));
assert.ok(result.issues.some((issue) => issue.id.startsWith("target:") && issue.can_auto_fix && issue.transformation_type === "increase_target"));
assert.ok(result.issues.some((issue) => issue.id.startsWith("contrast:") && issue.can_auto_fix && issue.transformation_type === "set_text_color"));
assert.ok(result.issues.some((issue) => issue.id.startsWith("name:") && !issue.can_auto_fix));
assert.ok(result.issues.some((issue) => issue.detected_by === "manual-review" && !issue.can_auto_fix));
console.log(`PASS deterministic audit: ${result.issueCount} findings across ${Object.keys(result.severity).join(", ")}`);
